// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function GetSerialPorts() {
  return window['go']['main']['App']['GetSerialPorts']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenJLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenJLink'](arg1, arg2, arg3);
}

export function OpenSerial(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OpenSerial'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenTcpClient(arg1, arg2) {
  return window['go']['main']['App']['OpenTcpClient'](arg1, arg2);
}

export function OpenTcpServer(arg1) {
  return window['go']['main']['App']['OpenTcpServer'](arg1);
}

export function OpenUdp(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenUdp'](arg1, arg2, arg3);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SendData(arg1) {
  return window['go']['main']['App']['SendData'](arg1);
}
